# Generated by Django 3.2.8 on 2021-11-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=11)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='crypto_model',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('field', multiselectfield.db.fields.MultiSelectField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('ADA', 'ADA'), ('SOL', 'SOL'), ('XRP', 'XRP')], max_length=23)),
            ],
        ),
    ]
