# Generated by Django 3.2.8 on 2021-11-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bit0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', multiselectfield.db.fields.MultiSelectField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('ADA', 'ADA'), ('SOL', 'SOL'), ('XRP', 'XRP')], max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
