# Generated by Django 3.2.8 on 2021-11-01 16:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0002_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('ADA', 'ADA'), ('SOL', 'SOL'), ('XRP', 'XRP')], max_length=23),
        ),
    ]
