# Generated by Django 3.2.8 on 2021-12-16 09:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0004_auto_20211201_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', multiselectfield.db.fields.MultiSelectField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('ADA', 'ADA'), ('SOL', 'SOL'), ('XRP', 'XRP')], max_length=23)),
            ],
        ),
    ]
