# Generated by Django 3.2.8 on 2021-11-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0004_rename_crypto_crypto_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto_model',
            name='user',
        ),
    ]
