# Generated by Django 3.2.8 on 2021-12-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0005_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hi',
        ),
    ]
