# Generated by Django 3.2.8 on 2021-12-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0006_delete_hi'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_number_model',
            fields=[
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bit0.crypto_model')),
            ],
        ),
    ]
