# Generated by Django 3.2.8 on 2021-12-22 17:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0009_alter_mobile_number_model_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_number_model',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None, unique=True),
        ),
    ]
