# Generated by Django 3.2.8 on 2021-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0010_alter_mobile_number_model_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.IntegerField(null=True)),
                ('ETH', models.IntegerField(null=True)),
                ('BNB', models.IntegerField(null=True)),
                ('ADA', models.IntegerField(null=True)),
                ('SOL', models.IntegerField(null=True)),
                ('XRP', models.IntegerField(null=True)),
            ],
        ),
    ]
