# Generated by Django 3.2.8 on 2021-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0011_price_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_model',
            name='ADA',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='BNB',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='BTC',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='ETH',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='SOL',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='XRP',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
