# Generated by Django 3.2.8 on 2021-12-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0014_alter_price_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_model',
            name='ADA',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='BNB',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='BTC',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='ETH',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='SOL',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price_model',
            name='XRP',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
