# Generated by Django 3.2.8 on 2021-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit0', '0015_auto_20211223_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_number_model',
            name='mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
